// <auto-generated />
using System;
using LoadBrokerageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoadBrokerageApp.Migrations
{
    [DbContext(typeof(LoadBrokerageDBContext))]
    partial class LoadBrokerageDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoadBrokerageApp.Models.Carriers", b =>
                {
                    b.Property<int>("CarriersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarriersId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CargoInsuranceCoverageAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContractExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractSignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DBAName")
                        .HasColumnType("text");

                    b.Property<string>("DOTComplianceScore")
                        .HasColumnType("text");

                    b.Property<string>("EIN_TaxID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ELDProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HazmatCertified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InsuranceExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsurancePolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LiabilityInsuraceCoverageAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoadsCompleted")
                        .HasColumnType("numeric");

                    b.Property<string>("MC_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingAuthority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingAuthorityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEquipmentType")
                        .HasColumnType("text");

                    b.Property<string>("State_Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("USDOT_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CarriersId");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("LoadBrokerageApp.Models.Loads", b =>
                {
                    b.Property<int>("LoadsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoadsId"));

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeAddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeContactPersonEmail")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeContactPersonPhone")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsigneePostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoadDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LoadPieceCount")
                        .HasColumnType("numeric");

                    b.Property<float>("LoadWeight")
                        .HasColumnType("real");

                    b.Property<decimal>("NumberOfStops")
                        .HasColumnType("numeric");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperAddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("ShipperContactPersonEmail")
                        .HasColumnType("text");

                    b.Property<string>("ShipperContactPersonPhone")
                        .HasColumnType("text");

                    b.Property<string>("ShipperId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoadsId");

                    b.ToTable("Loads");
                });

            modelBuilder.Entity("LoadBrokerageApp.Models.Shippers", b =>
                {
                    b.Property<int>("ShippersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShippersId"));

                    b.Property<DateTime?>("ContractExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractSignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LoadsCompleted")
                        .HasColumnType("numeric");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperAddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("ShipperContactPersonEmail")
                        .HasColumnType("text");

                    b.Property<string>("ShipperContactPersonPhone")
                        .HasColumnType("text");

                    b.Property<string>("ShipperPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipperState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShippersId");

                    b.ToTable("Shippers");
                });
#pragma warning restore 612, 618
        }
    }
}
